### ISSUE TITLE
Doesnt work on Windows

### ISSUE THREAD

**Issue by ryan-rocketsoftware** [Akryum/monorepo-run#9]
I have 10 team members who all use Windows laptops for development and all of them are getting the same error message when trying to run the mono-run test command. I am the only dev with a Mac and all of the mono-run commands work fine for me. Any idea on why the Windows machines cant run the library?

error:
Error: spawn UNKNOWN

stacktrace:
λ yarn run-test-all
yarn run v1.19.1
$ mono-run test --ui column
internal/child_process.js:366
   throw errnoException(err, 'spawn');
   ^
Error: spawn UNKNOWN
   at ChildProcess.spawn (internal/child_process.js:366:11)
   at Object.spawn (child_process.js:551:9)
   at Object.<anonymous> (C:\Users\jahuja\AppData\Roaming\npm\node_modules\monorepo-run\src\bin\mono-run.js:9:18)
   at Module._compile (internal/modules/cjs/loader.js:778:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
   at Module.load (internal/modules/cjs/loader.js:653:32)
   at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
   at Function.Module._load (internal/modules/cjs/loader.js:585:3)
   at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
   at startup (internal/bootstrap/node.js:283:19)
error Command failed with exit code 1.

**Comment by Akryum** [comment]
It should be fixed by https://github.com/Akryum/monorepo-run/commit/d977234b69a397d6c6abd506fce5ac29a5358b9f

**Comment by deraw** [comment]
Hi @Akryum!
First off, thank you for making this tool!
Do you know when a new version including this fix will be released?
Thanks

**Comment by steven-pribilinskiy** [comment]
I'm getting a similar issue
![image](https://user-images.githubusercontent.com/3078595/138659027-26529936-3362-4bc4-91f5-1ab0b9b2e7e5.png)
